/**
 * Markdown reporter - GitHub-flavored markdown output
 */

import type { TestReport } from '@reaatech/mcp-contract-core';
import { Severity } from '@reaatech/mcp-contract-core';

function severityBadge(severity: Severity): string {
  switch (severity) {
    case Severity.CRITICAL:
      return '🔴 CRITICAL';
    case Severity.WARNING:
      return '🟡 WARNING';
    case Severity.INFO:
      return '🟢 INFO';
    default:
      return '⚪ UNKNOWN';
  }
}

export function formatMarkdownReport(report: TestReport): string {
  const lines: string[] = [];

  // Header
  lines.push('# MCP Contract Kit - Test Report');
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');

  if (report.endpoint) {
    lines.push(`| Endpoint | \`${report.endpoint}\` |`);
  }
  lines.push(`| Timestamp | ${report.timestamp} |`);
  lines.push(`| Duration | ${report.durationMs}ms |`);
  lines.push(`| Status | ${report.passed ? '✅ PASSED' : '❌ FAILED'} |`);
  lines.push(`| Critical | ${report.failures.critical} |`);
  lines.push(`| Warnings | ${report.failures.warning} |`);
  lines.push(`| Info/Passed | ${report.failures.info} |`);
  lines.push('');

  // Connection error
  if (report.error) {
    lines.push('### Connection Error');
    lines.push('');
    lines.push(`> ${report.error}`);
    lines.push('');
  }

  // Results table
  lines.push('## Results');
  lines.push('');
  lines.push('| Validator | Status | Severity | Message |');
  lines.push('|-----------|--------|----------|---------|');

  for (const result of report.results) {
    const status = result.passed ? '✅ PASS' : '❌ FAIL';
    const message = result.message.replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(
      `| ${result.validator} | ${status} | ${severityBadge(result.severity)} | ${message} |`,
    );
  }

  lines.push('');

  // Detailed failures
  const failures = report.results.filter((r) => !r.passed);
  if (failures.length > 0) {
    lines.push('## Failures');
    lines.push('');

    for (const failure of failures) {
      lines.push(`### ${failure.validator}`);
      lines.push('');
      lines.push(`**Message:** ${failure.message}`);
      lines.push('');
      if (failure.remediation) {
        lines.push(`**Remediation:** ${failure.remediation}`);
        lines.push('');
      }
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [mcp-contract-kit](https://github.com/reaatech/mcp-contract-kit)*');

  return lines.join('\n');
}
