/**
 * HTML Reporter — generates an interactive HTML dashboard for test results
 */

import type { TestReport, TestResult } from '../types/domain.js';
import { Severity } from '../types/domain.js';

/**
 * Generate an HTML report from test results
 */
export async function generateHtmlReport(report: TestReport): Promise<string> {
  const timestamp = report.timestamp || new Date().toISOString();
  const duration = report.durationMs || 0;

  const totalTests = report.results.length;
  const passed = report.results.filter((r) => r.passed).length;
  const failed = report.results.filter((r) => !r.passed && r.severity === Severity.CRITICAL).length;
  const warnings = report.results.filter(
    (r) => !r.passed && r.severity === Severity.WARNING,
  ).length;
  const info = report.results.filter((r) => r.passed && r.severity === Severity.INFO).length;

  const statusColor = failed > 0 ? '#dc3545' : warnings > 0 ? '#fd7e14' : '#28a745';
  const statusText = failed > 0 ? 'FAILED' : warnings > 0 ? 'WARNINGS' : 'PASSED';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MCP Contract Kit - Test Report</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  background: #f5f5f5; color: #333; line-height: 1.6; padding: 24px;
}
.container { max-width: 960px; margin: 0 auto; }
h1 { font-size: 24px; margin-bottom: 8px; color: #1a1a2e; }
.subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
.header {
  background: #fff; border-radius: 8px; padding: 24px; margin-bottom: 16px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-left: 4px solid ${statusColor};
}
.header h1 { color: ${statusColor}; }
.summary-cards {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 12px; margin-bottom: 16px;
}
.card {
  background: #fff; border-radius: 8px; padding: 16px; text-align: center;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.card .value { font-size: 32px; font-weight: 700; }
.card .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
.card.total .value { color: #1a1a2e; }
.card.passed .value { color: #28a745; }
.card.failed .value { color: #dc3545; }
.card.warnings .value { color: #fd7e14; }
.card.info .value { color: #17a2b8; }
.test-list { background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.test-item {
  border-bottom: 1px solid #eee; padding: 16px 20px; cursor: pointer; transition: background 0.2s;
}
.test-item:hover { background: #f8f9fa; }
.test-item:last-child { border-bottom: none; }
.test-header { display: flex; align-items: center; gap: 12px; }
.test-icon { font-size: 20px; flex-shrink: 0; }
.test-name { font-weight: 600; flex: 1; }
.test-status {
  font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;
  padding: 2px 8px; border-radius: 4px;
}
.status-critical { background: #f8d7da; color: #721c24; }
.status-warning { background: #fff3cd; color: #856404; }
.status-info { background: #d1ecf1; color: #0c5460; }
.status-pass { background: #d4edda; color: #155724; }
.test-duration { font-size: 12px; color: #999; }
.test-details {
  display: none; margin-top: 12px; padding: 12px 16px; background: #f8f9fa;
  border-radius: 4px; font-size: 13px; line-height: 1.7;
}
.test-details.open { display: block; }
.test-details .message { color: #333; }
.test-details .remediation { margin-top: 8px; color: #856404; }
.test-details .remediation strong { display: block; margin-bottom: 4px; }
.footer { text-align: center; margin-top: 24px; color: #999; font-size: 12px; }
@media print { body { background: #fff; } .test-item { break-inside: avoid; } }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>⚙️ MCP Contract Kit — Test Report</h1>
    <p class="subtitle">Status: <strong>${statusText}</strong> · ${timestamp} · ${duration}ms</p>
  </div>

  <div class="summary-cards">
    <div class="card total"><div class="value">${totalTests}</div><div class="label">Total</div></div>
    <div class="card passed"><div class="value">${passed}</div><div class="label">Passed</div></div>
    <div class="card failed"><div class="value">${failed}</div><div class="label">Critical</div></div>
    <div class="card warnings"><div class="value">${warnings}</div><div class="label">Warnings</div></div>
    <div class="card info"><div class="value">${info}</div><div class="label">Info</div></div>
  </div>

  <div class="test-list">
    ${report.results.map((r) => renderTestItem(r)).join('')}
  </div>

  <div class="footer">
    Generated by <strong>mcp-contract-kit</strong> · <a href="https://github.com/mcp-contract-kit" style="color:#666">GitHub</a>
  </div>
</div>

<script>
document.querySelectorAll('.test-item').forEach(item => {
  item.addEventListener('click', () => {
    const details = item.querySelector('.test-details');
    details.classList.toggle('open');
  });
});
</script>
</body>
</html>`;
}

function renderTestItem(result: TestResult): string {
  const icon = result.passed
    ? '🟢'
    : result.severity === Severity.CRITICAL
      ? '🔴'
      : result.severity === Severity.WARNING
        ? '🟡'
        : '🔵';
  const statusClass = result.passed
    ? 'status-pass'
    : result.severity === Severity.CRITICAL
      ? 'status-critical'
      : result.severity === Severity.WARNING
        ? 'status-warning'
        : 'status-info';
  const statusLabel = result.passed ? 'PASS' : result.severity.toUpperCase();

  return `<div class="test-item">
    <div class="test-header">
      <span class="test-icon">${icon}</span>
      <span class="test-name">${escapeHtmlStr(result.validator)}</span>
      <span class="test-status ${statusClass}">${statusLabel}</span>
      <span class="test-duration">${result.durationMs}ms</span>
    </div>
    <div class="test-details">
      <div class="message">${escapeHtmlStr(result.message || 'No message')}</div>
      ${result.remediation ? `<div class="remediation"><strong>→ Remediation:</strong> ${escapeHtmlStr(result.remediation)}</div>` : ''}
      ${result.category ? `<div style="margin-top:8px;color:#666">Category: ${result.category}</div>` : ''}
    </div>
  </div>`;
}

function escapeHtmlStr(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
